import './styles/card.scss'
import './styles/styles.scss'
import './js/functions'
// import './js/classicFetch'
// import './js/train'
// import './js/train-class'
import './js/create-new-class'
import './js/optimization-class'
